SET SERVEROUTPUT ON SIZE UNLIMITED;
SET FEEDBACK ON;
SET ECHO ON;

WHENEVER SQLERROR EXIT FAILURE;

BEGIN
    DECLARE
       V_RC NUMBER;
    BEGIN
       UPDATE MY_STAGING_TABLE SET CREATED_DATE = SYSDATE;
       V_RC := SQL%ROWCOUNT;
       COMMIT;
       DBMS_OUTPUT.PUT_LINE('Affected line(s): '|| V_RC);
    EXCEPTION 
        WHEN OTHERS 
           THEN RAISE_APPLICATION_ERROR(-20001, SQLERRM);
    END;
END;
/

EXIT;
